"""Placed work sessions generated by the scheduler or recorded manually."""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING
from uuid import UUID, uuid4

from sqlalchemy import DateTime, ForeignKey, Index, String
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin
from app.models.enums import SessionSource, SessionStatus

if TYPE_CHECKING:
    from app.models.task import Task
    from app.models.user import User


class ScheduledSession(Base, TimestampMixin):
    __tablename__ = "scheduled_sessions"
    __table_args__ = (Index("ix_scheduled_sessions_user_start", "user_id", "start_at"),)

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        default=uuid4,
    )
    user_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    task_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    title_snapshot: Mapped[str] = mapped_column(String(512), nullable=False)
    start_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    end_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    source: Mapped[SessionSource] = mapped_column(
        SAEnum(SessionSource, name="session_source", native_enum=True),
        nullable=False,
        default=SessionSource.system_generated,
    )
    status: Mapped[SessionStatus] = mapped_column(
        SAEnum(SessionStatus, name="session_status", native_enum=True),
        nullable=False,
        default=SessionStatus.scheduled,
    )

    user: Mapped[User] = relationship(back_populates="scheduled_sessions")
    task: Mapped[Task] = relationship(back_populates="scheduled_sessions")
